version: "3.9"
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.6.2
    volumes:
      - ./logstash/config/logstash.conf:/usr/share/logstash/config/logstash.conf:ro
      #- ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - /var/log/GDPR/myapplication:/var/log/GDPR/myapplication:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elastic


networks:
  elastic:
    name: elastic
    driver: bridge
